# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'electiondetailsdialog.ui'
#
# Created: Thu Oct 23 19:48:55 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ElectionDetailsDialog(object):
    def setupUi(self, ElectionDetailsDialog):
        ElectionDetailsDialog.setObjectName(_fromUtf8("ElectionDetailsDialog"))
        ElectionDetailsDialog.resize(462, 502)
        self.gridLayout = QtGui.QGridLayout(ElectionDetailsDialog)
        self.gridLayout.setHorizontalSpacing(16)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_14 = QtGui.QLabel(ElectionDetailsDialog)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 2, 0, 1, 1)
        self.labelAmountVotes = QtGui.QLabel(ElectionDetailsDialog)
        self.labelAmountVotes.setObjectName(_fromUtf8("labelAmountVotes"))
        self.gridLayout.addWidget(self.labelAmountVotes, 12, 1, 1, 1)
        self.labelHash = QtGui.QLabel(ElectionDetailsDialog)
        self.labelHash.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.labelHash.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.labelHash.setObjectName(_fromUtf8("labelHash"))
        self.gridLayout.addWidget(self.labelHash, 2, 1, 1, 3)
        self.labelAmountVotesTooLate = QtGui.QLabel(ElectionDetailsDialog)
        self.labelAmountVotesTooLate.setObjectName(_fromUtf8("labelAmountVotesTooLate"))
        self.gridLayout.addWidget(self.labelAmountVotesTooLate, 12, 3, 1, 1)
        self.label_17 = QtGui.QLabel(ElectionDetailsDialog)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 16, 0, 1, 1)
        self.label_4 = QtGui.QLabel(ElectionDetailsDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_12 = QtGui.QLabel(ElectionDetailsDialog)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 14, 0, 1, 1)
        self.labelAmountCommitments = QtGui.QLabel(ElectionDetailsDialog)
        self.labelAmountCommitments.setObjectName(_fromUtf8("labelAmountCommitments"))
        self.gridLayout.addWidget(self.labelAmountCommitments, 14, 1, 1, 1)
        self.label_19 = QtGui.QLabel(ElectionDetailsDialog)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 22, 0, 1, 4)
        self.listWidgetAddresses = QtGui.QListWidget(ElectionDetailsDialog)
        self.listWidgetAddresses.setObjectName(_fromUtf8("listWidgetAddresses"))
        self.gridLayout.addWidget(self.listWidgetAddresses, 21, 0, 1, 4)
        self.label_3 = QtGui.QLabel(ElectionDetailsDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 9, 0, 1, 1)
        self.label_5 = QtGui.QLabel(ElectionDetailsDialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 10, 0, 1, 1)
        self.label_7 = QtGui.QLabel(ElectionDetailsDialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_15 = QtGui.QLabel(ElectionDetailsDialog)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 12, 2, 1, 1)
        self.label_8 = QtGui.QLabel(ElectionDetailsDialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.labelChanAddress = QtGui.QLabel(ElectionDetailsDialog)
        self.labelChanAddress.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.labelChanAddress.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.labelChanAddress.setObjectName(_fromUtf8("labelChanAddress"))
        self.gridLayout.addWidget(self.labelChanAddress, 3, 1, 1, 3)
        self.labelAmountPublicKeys = QtGui.QLabel(ElectionDetailsDialog)
        self.labelAmountPublicKeys.setObjectName(_fromUtf8("labelAmountPublicKeys"))
        self.gridLayout.addWidget(self.labelAmountPublicKeys, 10, 1, 1, 1)
        self.label_6 = QtGui.QLabel(ElectionDetailsDialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_9 = QtGui.QLabel(ElectionDetailsDialog)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 12, 0, 1, 1)
        self.labelBlockchain = QtGui.QLabel(ElectionDetailsDialog)
        self.labelBlockchain.setObjectName(_fromUtf8("labelBlockchain"))
        self.gridLayout.addWidget(self.labelBlockchain, 9, 3, 1, 1)
        self.labelStartTime = QtGui.QLabel(ElectionDetailsDialog)
        self.labelStartTime.setObjectName(_fromUtf8("labelStartTime"))
        self.gridLayout.addWidget(self.labelStartTime, 5, 1, 1, 1)
        self.labelQuestion = QtGui.QLabel(ElectionDetailsDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelQuestion.setFont(font)
        self.labelQuestion.setObjectName(_fromUtf8("labelQuestion"))
        self.gridLayout.addWidget(self.labelQuestion, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(ElectionDetailsDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 20, 0, 1, 4)
        self.label_16 = QtGui.QLabel(ElectionDetailsDialog)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 7, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ElectionDetailsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 23, 0, 1, 4)
        self.labelDeadline = QtGui.QLabel(ElectionDetailsDialog)
        self.labelDeadline.setObjectName(_fromUtf8("labelDeadline"))
        self.gridLayout.addWidget(self.labelDeadline, 6, 1, 1, 1)
        self.labelAmountAddresses = QtGui.QLabel(ElectionDetailsDialog)
        self.labelAmountAddresses.setObjectName(_fromUtf8("labelAmountAddresses"))
        self.gridLayout.addWidget(self.labelAmountAddresses, 9, 1, 1, 1)
        self.labelCommitmentPhaseDeadline = QtGui.QLabel(ElectionDetailsDialog)
        self.labelCommitmentPhaseDeadline.setObjectName(_fromUtf8("labelCommitmentPhaseDeadline"))
        self.gridLayout.addWidget(self.labelCommitmentPhaseDeadline, 7, 1, 1, 1)
        self.label_10 = QtGui.QLabel(ElectionDetailsDialog)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 9, 2, 1, 1)
        self.label = QtGui.QLabel(ElectionDetailsDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.labelStatus = QtGui.QLabel(ElectionDetailsDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelStatus.setFont(font)
        self.labelStatus.setObjectName(_fromUtf8("labelStatus"))
        self.gridLayout.addWidget(self.labelStatus, 0, 3, 1, 1)
        self.labelAmountMissingValidVotes = QtGui.QLabel(ElectionDetailsDialog)
        self.labelAmountMissingValidVotes.setObjectName(_fromUtf8("labelAmountMissingValidVotes"))
        self.gridLayout.addWidget(self.labelAmountMissingValidVotes, 14, 3, 1, 1)
        self.label_18 = QtGui.QLabel(ElectionDetailsDialog)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 14, 2, 1, 1)
        self.labelAmountResults = QtGui.QLabel(ElectionDetailsDialog)
        self.labelAmountResults.setObjectName(_fromUtf8("labelAmountResults"))
        self.gridLayout.addWidget(self.labelAmountResults, 16, 1, 1, 1)
        self.frame_6 = QtGui.QFrame(ElectionDetailsDialog)
        self.frame_6.setFrameShape(QtGui.QFrame.HLine)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout.addWidget(self.frame_6, 13, 0, 1, 4)
        self.frame_3 = QtGui.QFrame(ElectionDetailsDialog)
        self.frame_3.setFrameShape(QtGui.QFrame.HLine)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout.addWidget(self.frame_3, 11, 0, 1, 4)
        self.frame_5 = QtGui.QFrame(ElectionDetailsDialog)
        self.frame_5.setFrameShape(QtGui.QFrame.HLine)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout.addWidget(self.frame_5, 8, 0, 1, 4)
        self.frame_4 = QtGui.QFrame(ElectionDetailsDialog)
        self.frame_4.setFrameShape(QtGui.QFrame.HLine)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout.addWidget(self.frame_4, 4, 0, 1, 4)
        self.frame_2 = QtGui.QFrame(ElectionDetailsDialog)
        self.frame_2.setFrameShape(QtGui.QFrame.HLine)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout.addWidget(self.frame_2, 19, 0, 1, 4)
        self.frame = QtGui.QFrame(ElectionDetailsDialog)
        self.frame.setFrameShape(QtGui.QFrame.HLine)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 4)
        self.label_13 = QtGui.QLabel(ElectionDetailsDialog)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 15, 0, 1, 1)
        self.label_11 = QtGui.QLabel(ElectionDetailsDialog)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 15, 2, 1, 1)
        self.labelAmountVotesValidatedFromCommitments = QtGui.QLabel(ElectionDetailsDialog)
        self.labelAmountVotesValidatedFromCommitments.setObjectName(_fromUtf8("labelAmountVotesValidatedFromCommitments"))
        self.gridLayout.addWidget(self.labelAmountVotesValidatedFromCommitments, 15, 3, 1, 1)
        self.labelAmountInvalidCommitments = QtGui.QLabel(ElectionDetailsDialog)
        self.labelAmountInvalidCommitments.setObjectName(_fromUtf8("labelAmountInvalidCommitments"))
        self.gridLayout.addWidget(self.labelAmountInvalidCommitments, 15, 1, 1, 1)

        self.retranslateUi(ElectionDetailsDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ElectionDetailsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ElectionDetailsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ElectionDetailsDialog)

    def retranslateUi(self, ElectionDetailsDialog):
        ElectionDetailsDialog.setWindowTitle(_translate("ElectionDetailsDialog", "Dialog", None))
        self.label_14.setText(_translate("ElectionDetailsDialog", "Election hash: ", None))
        self.labelAmountVotes.setText(_translate("ElectionDetailsDialog", "N/A", None))
        self.labelHash.setText(_translate("ElectionDetailsDialog", "N/A", None))
        self.labelAmountVotesTooLate.setText(_translate("ElectionDetailsDialog", "N/A", None))
        self.label_17.setText(_translate("ElectionDetailsDialog", "# Results: ", None))
        self.label_4.setText(_translate("ElectionDetailsDialog", "Status: ", None))
        self.label_12.setText(_translate("ElectionDetailsDialog", "# Commitments: ", None))
        self.labelAmountCommitments.setText(_translate("ElectionDetailsDialog", "N/A", None))
        self.label_19.setText(_translate("ElectionDetailsDialog", "<br><sup>1</sup> These times are defined as adjusted block timestamps on the blockchain and as such are only estimates.<br>", None))
        self.label_3.setText(_translate("ElectionDetailsDialog", "# Addresses:", None))
        self.label_5.setText(_translate("ElectionDetailsDialog", "# Public keys", None))
        self.label_7.setText(_translate("ElectionDetailsDialog", "Start time<sup>1</sup>:", None))
        self.label_15.setText(_translate("ElectionDetailsDialog", "# Votes too late: ", None))
        self.label_8.setText(_translate("ElectionDetailsDialog", "Deadline<sup>1</sup>:", None))
        self.labelChanAddress.setText(_translate("ElectionDetailsDialog", "N/A", None))
        self.labelAmountPublicKeys.setText(_translate("ElectionDetailsDialog", "N/A", None))
        self.label_6.setText(_translate("ElectionDetailsDialog", "Chan address: ", None))
        self.label_9.setText(_translate("ElectionDetailsDialog", "# Valid votes: ", None))
        self.labelBlockchain.setText(_translate("ElectionDetailsDialog", "N/A", None))
        self.labelStartTime.setText(_translate("ElectionDetailsDialog", "N/A", None))
        self.labelQuestion.setText(_translate("ElectionDetailsDialog", "N/A", None))
        self.label_2.setText(_translate("ElectionDetailsDialog", "Registered addresses:", None))
        self.label_16.setText(_translate("ElectionDetailsDialog", "Commitment phase<br>deadline<sup>1</sup>:", None))
        self.labelDeadline.setText(_translate("ElectionDetailsDialog", "N/A", None))
        self.labelAmountAddresses.setText(_translate("ElectionDetailsDialog", "N/A", None))
        self.labelCommitmentPhaseDeadline.setText(_translate("ElectionDetailsDialog", "N/A", None))
        self.label_10.setText(_translate("ElectionDetailsDialog", "Blockchain: ", None))
        self.label.setText(_translate("ElectionDetailsDialog", "Question: ", None))
        self.labelStatus.setText(_translate("ElectionDetailsDialog", "N/A", None))
        self.labelAmountMissingValidVotes.setText(_translate("ElectionDetailsDialog", "N/A", None))
        self.label_18.setText(_translate("ElectionDetailsDialog", "# Missing valid votes:", None))
        self.labelAmountResults.setText(_translate("ElectionDetailsDialog", "N/A", None))
        self.label_13.setText(_translate("ElectionDetailsDialog", "# Invalid\n"
"commitments:", None))
        self.label_11.setText(_translate("ElectionDetailsDialog", "# Votes validated\n"
"from commitments:", None))
        self.labelAmountVotesValidatedFromCommitments.setText(_translate("ElectionDetailsDialog", "N/A", None))
        self.labelAmountInvalidCommitments.setText(_translate("ElectionDetailsDialog", "N/A", None))

